services:
  - type: web
    name: charanjit-properties
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_USERNAME
        value: charanjit
      - key: ADMIN_PASSWORD
        value: Channi@2026
      - key: NODE_ENV
        value: production
